// One-time data generator: pulls the full National Pokédex (id, name, types,
// generation) from PokéAPI and writes src/data/pokedex.generated.ts.
//
// Run with:  node scripts/build-pokedex.mjs
//
// The generated file is committed so the app builds with no network access;
// PokéAPI is only hit client-side for extra per-Pokémon flavour data.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const MAX_DEX = 1025; // base National Dex entries (forms have ids >= 10000)
const CONCURRENCY = 24;

// National Dex ranges per game generation.
const GEN_RANGES = [
  [1, 151, 1], [152, 251, 2], [252, 386, 3], [387, 493, 4], [494, 649, 5],
  [650, 721, 6], [722, 809, 7], [810, 905, 8], [906, 1025, 9],
];
const genFor = (id) => GEN_RANGES.find(([a, b]) => id >= a && id <= b)?.[2] ?? 0;

// Display-name fixups where PokéAPI's slug doesn't title-case cleanly.
const NAME_OVERRIDES = {
  "nidoran-f": "Nidoran♀", "nidoran-m": "Nidoran♂",
  "mr-mime": "Mr. Mime", "mime-jr": "Mime Jr.", "mr-rime": "Mr. Rime",
  "type-null": "Type: Null", "farfetchd": "Farfetch'd", "sirfetchd": "Sirfetch'd",
  "tapu-koko": "Tapu Koko", "tapu-lele": "Tapu Lele",
  "tapu-bulu": "Tapu Bulu", "tapu-fini": "Tapu Fini", "flabebe": "Flabébé",
};

function displayName(slug) {
  if (NAME_OVERRIDES[slug]) return NAME_OVERRIDES[slug];
  // Title-case, keep hyphens (Ho-Oh, Porygon-Z, Jangmo-o, Kommo-o).
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("-");
}

async function fetchOne(id) {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
  if (!res.ok) throw new Error(`id ${id} -> HTTP ${res.status}`);
  const j = await res.json();
  return {
    dexId: id,
    name: displayName(j.name),
    types: j.types.sort((a, b) => a.slot - b.slot).map((t) => t.type.name),
    generation: genFor(id),
  };
}

const results = new Array(MAX_DEX).fill(null);
let nextId = 1;

async function worker() {
  while (true) {
    const id = nextId++;
    if (id > MAX_DEX) return;
    for (let attempt = 1; ; attempt++) {
      try {
        results[id - 1] = await fetchOne(id);
        break;
      } catch (err) {
        if (attempt >= 4) {
          console.error("FAILED", id, err.message);
          break;
        }
        await new Promise((r) => setTimeout(r, 400 * attempt));
      }
    }
  }
}

console.log(`Fetching ${MAX_DEX} Pokémon from PokéAPI (concurrency ${CONCURRENCY})…`);
await Promise.all(Array.from({ length: CONCURRENCY }, worker));

const dex = results.filter(Boolean);
console.log(`Got ${dex.length}/${MAX_DEX}.`);
if (dex.length < MAX_DEX) {
  console.error("Some entries missing — aborting so we don't write a partial dex.");
  process.exit(1);
}

const body = dex
  .map((p) => `  { dexId: ${p.dexId}, name: ${JSON.stringify(p.name)}, types: ${JSON.stringify(p.types)}, generation: ${p.generation} },`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/build-pokedex.mjs — do not edit by hand.
// Source: PokéAPI (https://pokeapi.co). National Dex 1–${MAX_DEX}.
import type { PokemonType } from "@/lib/types";

export interface PokedexEntry {
  dexId: number;
  name: string;
  types: PokemonType[];
  generation: number;
}

export const POKEDEX: PokedexEntry[] = [
${body}
];
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "src", "data", "pokedex.generated.ts");
await writeFile(target, out, "utf8");
console.log(`Wrote ${target}`);
